drop table if exists bookmarks;

create table bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT,
  url TEXT, 
  description TEXT, 
  rating INTEGER
);

insert into bookmarks 
(title, url, description, rating)
values 
(
  'GitHub',
  'https://www.github.com',
  'build projects',
  5
),
(
  'Gmail',
  'https://www.gmail.com',
  'send emails',
  3
), 
(
  'Intro to SQL',
  'https://courses.thinkful.com/ei-node-postgres-v1/checkpoint/12',
  'learn cool stuff',
  2
),
(
  'SQLZOO Drills', 
  'https://sqlzoo.net/wiki/SELECT_basics',
  'Drills for SQL',
  5
),
(
  'Whats it like?', 
  'https://open.spotify.com/album/5LJzP85Zn7B2IAt7zhLImG',
  'Sure Sure album',
  5
),
(
  'Netflix', 
  'https://netflix.com',
  'To waste your life',
  1 
),
(
  'SASS Drills', 
  'https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables/',
  'Get sassy!',
  3 
),
(
  'Letterboxd', 
  'https://letterboxd.com/welcome/',
  'Rate cool movies',
  2
),
(
  'Goodreads', 
  'https://www.goodreads.com/',
  'Rate cool books',
  2 
),
(
  'Gmail', 
  'https://mail.google.com/mail/u/0/',
  'Get junk mail',
  3
),
(
  'Reddit', 
  'https://reddit.com',
  'frontpage of the internet',
  3
);